# Generated by Django 3.2.9 on 2021-12-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surveys',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=40)),
                ('surveyData', models.JSONField()),
                ('author', models.CharField(max_length=40)),
                ('modify_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
