# Generated by Django 3.2.9 on 2022-06-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_surveyresults'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveys',
            name='color',
            field=models.CharField(default='#fff', max_length=40),
        ),
    ]
