# Generated by Django 3.2.9 on 2022-03-24 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contactName', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessSteps',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('processName', models.CharField(default='', max_length=50)),
                ('idDone', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolProcess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('schedule', models.TextField(default='')),
                ('contactID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_name', to='core.contact')),
                ('processID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processStep_name', to='core.processsteps')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('taskName', models.CharField(default='', max_length=50)),
                ('idDone', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='school',
            name='contact_info_email',
        ),
        migrations.RemoveField(
            model_name='school',
            name='contact_info_image',
        ),
        migrations.RemoveField(
            model_name='school',
            name='contact_info_name',
        ),
        migrations.RemoveField(
            model_name='school',
            name='contact_info_phone_number',
        ),
        migrations.RemoveField(
            model_name='school',
            name='school_location',
        ),
        migrations.RemoveField(
            model_name='school',
            name='school_name',
        ),
        migrations.RemoveField(
            model_name='school',
            name='school_region',
        ),
        migrations.AddField(
            model_name='school',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='consultant',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='district',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='noOfStudents',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='noOfTeachers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='phoneNo',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.AddField(
            model_name='school',
            name='pic',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='school',
            name='psychologist',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='schoolName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='Process',
        ),
        migrations.AddField(
            model_name='schoolprocess',
            name='schoolID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_name', to='core.school'),
        ),
        migrations.AddField(
            model_name='processsteps',
            name='taskID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_name', to='core.task'),
        ),
    ]
